name: Ruff
run-name: ${{ github.workflow }} - ${{ github.event.pull_request.title }}

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: ${{ github.workflow }}-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  Lint-and-Format:
    name: Lint and Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7.3.0
        with:
          enable-cache: false
          version: "latest"

      - name: Install Ruff
        run: uv tool install 'ruff==0.14.14'

      - name: Run Ruff check
        run: uv tool run ruff check --output-format=github --exit-non-zero-on-fix .

      - name: Run Ruff format check
        run: uv tool run ruff format --check .
