name: Semantic Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout release branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}
          token: ${{ secrets.GH_PAT_TOKEN }}

      - name: Force release branch to workflow SHA
        run: git reset --hard ${{ github.sha }}

      - name: Verify upstream has not changed
        shell: bash
        run: |
          set +o pipefail

          UPSTREAM_BRANCH_NAME="$(git status -sb | head -n 1 | cut -d' ' -f2 | grep -E '\.{3}' | cut -d'.' -f4)"
          echo "Upstream branch name: $UPSTREAM_BRANCH_NAME"

          set -o pipefail

          if [ -z "$UPSTREAM_BRANCH_NAME" ]; then
              echo "::error::Unable to determine upstream branch name!"
              exit 1
          fi

          git fetch "${UPSTREAM_BRANCH_NAME%%/*}"

          if ! UPSTREAM_SHA="$(git rev-parse "$UPSTREAM_BRANCH_NAME")"; then
              echo "::error::Unable to determine upstream branch SHA!"
              exit 1
          fi

          HEAD_SHA="$(git rev-parse HEAD)"

          if [ "$HEAD_SHA" != "$UPSTREAM_SHA" ]; then
              echo "[HEAD SHA] $HEAD_SHA != $UPSTREAM_SHA [UPSTREAM SHA]"
              echo "::error::Upstream has changed, aborting release..."
              exit 1
          fi

      - name: Set branch name in package.json
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          node -e "let pkg = require('./package.json'); pkg.branch_name = '${BRANCH_NAME}'; require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));"

      - name: Semantic release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 25.0.5
          branches: |
            [
              'main',
            ]
          tag_format: v${ version }+${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_TOKEN }}
